In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


In [7]:
import torch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [10]:
t = torch.FloatTensor([[1., 2., 3.],
                     [4., 5., 6.],
                     [7., 8., 9.],
                     [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [12]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [13]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [14]:
print(t[:-1, :-1])

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


## 브로드캐스팅

In [15]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 +m2)

tensor([[5., 5.]])


In [16]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [17]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### 자주 사용되는 기능들

In [18]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [19]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [21]:
print(t.mean(dim=0))

tensor([2., 3.])


In [22]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [23]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [40]:
t = torch.arange(2*3*4).view(2,3,4)
print(t)
print(t.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


In [48]:
t = torch.arange(4*6).view(4,6)
print(t)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [50]:
t = torch.FloatTensor([[1, 2], [3, 4]])

In [51]:
print(t.mean())

tensor(2.5000)


In [53]:
print(t.mean(1))

tensor([1.5000, 3.5000])


In [54]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [55]:
print(ft.shape)

torch.Size([2, 2, 3])


In [56]:
print(ft.view(-1,3))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [57]:
print(ft.view(-1,1,3))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [60]:
t = torch.FloatTensor([[1], [2], [3]])
print(t)

tensor([[1.],
        [2.],
        [3.]])


In [61]:
t.size()

torch.Size([3, 1])

In [63]:
print(t.squeeze())
print(t.squeeze().shape)

tensor([1., 2., 3.])
torch.Size([3])


In [66]:
print(t.unsqueeze(0))
print(t.unsqueeze(0).shape)
print(t.view(1, -1))
print(t.view(1, -1).shape)

tensor([[[1.],
         [2.],
         [3.]]])
torch.Size([1, 3, 1])
tensor([[1., 2., 3.]])
torch.Size([1, 3])


### 타입 캐스팅

In [67]:
lt = torch.LongTensor(1, 2, 3, 4)
print(lt)

tensor([[[[ 1001398616111781186,        2409364258416,        2409364262144,
            6661300707627057634],
          [       2409364258480,        2409364262192, -5875927596084039877,
                  2409364258544],
          [       2409364262240, -6359674735840546411,        2409364258608,
                  2409364262288]],

         [[ 7647447891852453841,        2409364258672,        2409364262336,
           -7764786772962753348],
          [       2409364258736,        2409364262384, -8002481185704664628,
                  2409364271152],
          [       2409364262432,  1618633955012741222,        2409364271216,
                  2409364262480]]]])


In [68]:
print(lt.float())

tensor([[[[ 1.0014e+18,  2.4094e+12,  2.4094e+12,  6.6613e+18],
          [ 2.4094e+12,  2.4094e+12, -5.8759e+18,  2.4094e+12],
          [ 2.4094e+12, -6.3597e+18,  2.4094e+12,  2.4094e+12]],

         [[ 7.6474e+18,  2.4094e+12,  2.4094e+12, -7.7648e+18],
          [ 2.4094e+12,  2.4094e+12, -8.0025e+18,  2.4094e+12],
          [ 2.4094e+12,  1.6186e+18,  2.4094e+12,  2.4094e+12]]]])


In [69]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [70]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate & stacking

In [73]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [74]:
print(torch.cat([x, y], 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [75]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [76]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### In-place Operation

In [77]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [78]:
print(x.mul_(2,))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
